config/routes.rb
Rails.application.routes.draw do
  get 'doctors/new'

  get 'admin/index'

 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'static_pages#home'

  get 'root' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' =>  'users#new'
  get 'docsign' => 'doctors#new'
  resources:users
  resources:doctors
  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
   def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def new
    @doc = Doctor.new
  end
  
  def create
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

  user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
       log_in user
       params[:session][:remember_me] == '1' ? remember(user) : forget(user)
       remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	 log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _error_messages
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
      log_in @user
      
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
	def log_in(user)
    session[:user_id] = user.id
  end

   def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
   
  end
  
 def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  

   def log_out
   	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

   def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
     def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/doctors/new.html.erb
<% provide(:title,' Doctor Signup')  %>

<h1>Doctor - Register for a New Account</h1>
    
<div class="row">
 
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@doc) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name,class: 'form-control',placeholder: "Name" %><br>

      <%= f.label :email%>
      <%= f.email_field :email,class: 'form-control',placeholder: " EmailID" %><br>

      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control',placeholder: " Password"%><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation,class:  'form-control',placeholder: "ReEnter Password" %><br>
 
 
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    developed by <%= link_to "Mediconsultant pvt ltd","www.Mediconsultant.co.in" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About us",   'about' %></li>
      <li><%= link_to "Contact us", 'contact' %></li>
     
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
       
    
    <nav>
    <h3>  <%= link_to "Speakmedicare.com", 'root', id: "logo" %></h3>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   'root' %></li>
       
       <% if logged_in? %> 
       <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Update Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
            <% else %>
           <li><%= link_to "Consult a Doctor Now",   login_path %></li>
           <li><%= link_to "Are you a Doctor?", docsign_path %></li>

          
           <% end %>
  </ul>
       
    
  </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title) %> |  speakmedicare.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <% flash.each do |message_type, message| %>
       <h2> <div  class="alert alert-danger"-<%= message_type %>"><%= message %></div></h2>
      <% end %>
   <%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About us") %>


<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact us") %>

<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>



<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
         <%= image_tag("pic02.jpg", :alt => "rss feed") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to Speakmedicare.com.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag("pic03.jpg", :alt => "rss feed") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
        <div class="item">
        <%= image_tag("pic04.jpg", :alt => "rss feed") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
<div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4 center">
          <h2>Ask a Doctor</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><%= link_to "View Details", '#', class: "btn btn-success" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4 center">

          <h2>Phone Consultation</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><%= link_to "View Details", '#', class: "btn btn-success" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4  center ">
          
          <h2>Video Consultation</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><%= link_to "View Details", '#', class: "btn btn-success" %></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


  
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title,'Signup')  %>

<h1>Sign up</h1>


    
    
    
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name,class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email,class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation,class:  'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
 

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>